from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import sys
import uuid
from dataclasses import asdict, dataclass
from pathlib import Path

from _skillmeta import SkillMetadata, parse_skill_metadata
from _workflowlib import load_json_object, resolve_under, sha256_file, write_bytes_atomic, write_json_atomic


METHOD_SKILLS = {
    "brainstorming", "dispatching-parallel-agents", "executing-plans",
    "finishing-a-development-branch", "receiving-code-review", "requesting-code-review",
    "subagent-driven-development", "systematic-debugging", "test-driven-development",
    "using-git-worktrees", "using-superpowers", "verification-before-completion",
    "writing-plans", "writing-skills",
}
LIFECYCLE_SKILLS = {
    "project-kickoff", "project-organization", "project-development", "project-continuity", "project-maintenance",
    "project-verification", "project-security", "maintaining-project-docs", "project-release",
    "project-incident-response", "project-research",
}
REQUIRED_SKILLS = METHOD_SKILLS | LIFECYCLE_SKILLS
LOCK_PATH = ".ai-workflow/ADAPTERS.lock.json"
PROXY_PATH = re.compile(r"^\.claude/skills/([a-z0-9]+(?:-[a-z0-9]+)*)/SKILL\.md$")


@dataclass(frozen=True)
class AdapterOperation:
    path: str
    action: str
    expected_sha256: str | None
    reason: str


def render_claude_root() -> bytes:
    return b"<!-- Generated by .ai-workflow/scripts/sync_adapters.py; do not edit. -->\n@AGENTS.md\n"


def render_gemini_root() -> bytes:
    return b"<!-- Generated by .ai-workflow/scripts/sync_adapters.py; do not edit. -->\n@./AGENTS.md\n"


def render_claude_proxy(meta: SkillMetadata) -> bytes:
    description = json.dumps(meta.description, ensure_ascii=False)
    text = (
        f"---\nname: {meta.name}\ndescription: {description}\n---\n\n"
        f"Read `../../../.agents/skills/{meta.name}/SKILL.md` completely before acting. "
        "Resolve every relative resource from that canonical Skill directory.\n"
    )
    return text.encode("utf-8")


def _digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _reject_symlink_components(root: Path, path: Path) -> None:
    root = root.resolve()
    try:
        relative = path.absolute().relative_to(root)
    except ValueError as error:
        raise ValueError("adapter target escapes root") from error
    current = root
    for part in relative.parts:
        current = current / part
        if current.is_symlink():
            raise ValueError(f"adapter path contains symlink: {relative.as_posix()}")


def _canonical_skills(
    root: Path,
    require_complete: bool,
    allow_extra_skills: bool,
) -> tuple[dict[str, tuple[SkillMetadata, str]], set[str]]:
    skills_root = root / ".agents/skills"
    if not skills_root.is_dir() or skills_root.is_symlink():
        raise ValueError("missing or unsafe canonical skill root")
    result: dict[str, tuple[SkillMetadata, str]] = {}
    for child in sorted(skills_root.iterdir(), key=lambda path: path.name):
        if child.is_symlink():
            raise ValueError(f"canonical skill is a symlink: {child.name}")
        if not child.is_dir():
            continue
        skill_file = child / "SKILL.md"
        if not skill_file.is_file() or skill_file.is_symlink():
            continue
        meta = parse_skill_metadata(skill_file)
        result[meta.name] = (meta, sha256_file(skill_file))
    names = set(result)
    missing = sorted(REQUIRED_SKILLS - names)
    unexpected = sorted(names - REQUIRED_SKILLS)
    if allow_extra_skills:
        if not require_complete:
            raise ValueError("allow_extra_skills requires the complete canonical Skill set")
        if missing:
            raise ValueError(f"canonical Skill set incomplete; missing={missing}")
        return {name: result[name] for name in sorted(REQUIRED_SKILLS)}, set(unexpected)
    if require_complete and names != REQUIRED_SKILLS:
        raise ValueError(f"canonical Skill set incomplete; missing={missing}; unexpected={unexpected}")
    return result, set()


def _load_lock(root: Path) -> dict[str, dict[str, str]]:
    path = root / LOCK_PATH
    if not path.exists():
        return {}
    if path.is_symlink():
        raise ValueError("adapter lock is a symlink")
    value = load_json_object(path, "adapter lock")
    if set(value) != {"schema_version", "generated"} or value["schema_version"] != 1:
        raise ValueError("invalid adapter lock schema")
    generated = value["generated"]
    if not isinstance(generated, dict):
        raise ValueError("adapter lock generated must be an object")
    result: dict[str, dict[str, str]] = {}
    for relative, record in generated.items():
        if not isinstance(relative, str) or not isinstance(record, dict):
            raise ValueError("invalid adapter lock entry")
        if set(record) != {"sha256", "source_fingerprint"}:
            raise ValueError("invalid adapter lock entry fields")
        if not all(isinstance(record[key], str) and len(record[key]) == 64 for key in record):
            raise ValueError("invalid adapter lock hash")
        if relative not in {"CLAUDE.md", "GEMINI.md"} and PROXY_PATH.fullmatch(relative) is None:
            raise ValueError(f"adapter lock path is not generated by this engine: {relative}")
        resolve_under(root, relative)
        result[relative] = {"sha256": record["sha256"], "source_fingerprint": record["source_fingerprint"]}
    return result


def _expected_outputs(
    root: Path,
    require_complete: bool,
    allow_extra_skills: bool = False,
) -> tuple[dict[str, tuple[bytes, str]], set[str]]:
    if not (root / "AGENTS.md").is_file() or (root / "AGENTS.md").is_symlink():
        raise ValueError("missing or unsafe AGENTS.md")
    skills, extra_skills = _canonical_skills(
        root,
        require_complete=require_complete,
        allow_extra_skills=allow_extra_skills,
    )
    agents_hash = sha256_file(root / "AGENTS.md")
    outputs = {
        "CLAUDE.md": (render_claude_root(), agents_hash),
        "GEMINI.md": (render_gemini_root(), agents_hash),
    }
    for name, (meta, source_hash) in skills.items():
        outputs[f".claude/skills/{name}/SKILL.md"] = (render_claude_proxy(meta), source_hash)
    return outputs, extra_skills


def build_adapter_plan(
    root: Path,
    require_complete: bool = True,
    *,
    allow_extra_skills: bool = False,
) -> list[AdapterOperation]:
    root = root.resolve()
    expected, extra_skills = _expected_outputs(
        root,
        require_complete=require_complete,
        allow_extra_skills=allow_extra_skills,
    )
    locked = _load_lock(root)
    ignored_locked = {
        f".claude/skills/{name}/SKILL.md"
        for name in extra_skills
    }
    managed_locked = {relative: record for relative, record in locked.items() if relative not in ignored_locked}
    operations: list[AdapterOperation] = []
    for relative in sorted(expected):
        data, _ = expected[relative]
        expected_hash = _digest(data)
        target = resolve_under(root, relative)
        _reject_symlink_components(root, target)
        record = managed_locked.get(relative)
        if not target.exists():
            operations.append(AdapterOperation(relative, "create", expected_hash, "generated target is absent"))
        elif not target.is_file():
            operations.append(AdapterOperation(relative, "conflict", expected_hash, "generated target is not a regular file"))
        elif record is None:
            operations.append(AdapterOperation(relative, "conflict", expected_hash, "existing target is not recorded in adapter lock"))
        else:
            current_hash = sha256_file(target)
            if current_hash != record["sha256"]:
                operations.append(AdapterOperation(relative, "conflict", expected_hash, "target differs from locked generated bytes"))
            elif current_hash == expected_hash and record["source_fingerprint"] == expected[relative][1]:
                operations.append(AdapterOperation(relative, "unchanged", expected_hash, "target matches canonical input"))
            else:
                operations.append(AdapterOperation(relative, "update", expected_hash, "canonical input changed"))
    for relative in sorted(set(managed_locked) - set(expected)):
        target = resolve_under(root, relative)
        _reject_symlink_components(root, target)
        record = managed_locked[relative]
        if not target.exists():
            operations.append(AdapterOperation(relative, "remove", None, "stale target already absent"))
        elif not target.is_file() or sha256_file(target) != record["sha256"]:
            operations.append(AdapterOperation(relative, "conflict", None, "stale target was modified"))
        else:
            operations.append(AdapterOperation(relative, "remove", None, "canonical Skill was removed"))
    return sorted(operations, key=lambda operation: operation.path)


def apply_adapter_plan(
    root: Path,
    plan: list[AdapterOperation],
    *,
    allow_extra_skills: bool = False,
) -> None:
    root = root.resolve()
    if any(operation.action == "conflict" for operation in plan):
        raise ValueError("adapter plan contains conflicts; no files written")
    fresh = build_adapter_plan(root, allow_extra_skills=allow_extra_skills)
    if fresh != plan:
        raise ValueError("adapter inputs changed after planning; no files written")
    expected, extra_skills = _expected_outputs(
        root,
        require_complete=True,
        allow_extra_skills=allow_extra_skills,
    )
    locked = _load_lock(root)
    preserved = {
        relative: record
        for relative, record in locked.items()
        if PROXY_PATH.fullmatch(relative) is not None
        and PROXY_PATH.fullmatch(relative).group(1) in extra_skills
    }
    generated = {
        relative: {"sha256": _digest(data), "source_fingerprint": source_hash}
        for relative, (data, source_hash) in sorted(expected.items())
    }
    generated.update(preserved)
    lock_bytes = (json.dumps({"schema_version": 1, "generated": generated}, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8")
    writes = {
        operation.path: expected[operation.path][0]
        for operation in plan
        if operation.action in {"create", "update"}
    }
    writes[LOCK_PATH] = lock_bytes
    removals = {operation.path for operation in plan if operation.action == "remove"}
    transaction = resolve_under(root, f".ai-workflow/.tmp/adapter-{uuid.uuid4().hex}")
    workflow_existed = (root / ".ai-workflow").exists()
    staged: dict[str, Path] = {}
    backups: dict[str, Path | None] = {}
    affected = sorted(set(writes) | removals)
    try:
        transaction.mkdir(parents=True, exist_ok=False)
        for index, (relative, data) in enumerate(sorted(writes.items())):
            stage = transaction / "stage" / f"{index:04d}"
            write_bytes_atomic(stage, data)
            staged[relative] = stage
        for index, relative in enumerate(affected):
            target = resolve_under(root, relative)
            _reject_symlink_components(root, target)
            backup = transaction / "backup" / f"{index:04d}"
            if target.exists():
                if not target.is_file():
                    raise OSError(f"adapter target is not a regular file: {relative}")
                backup.parent.mkdir(parents=True, exist_ok=True)
                os.replace(target, backup)
                backups[relative] = backup
            else:
                backups[relative] = None
            if relative in writes:
                target.parent.mkdir(parents=True, exist_ok=True)
                _reject_symlink_components(root, target)
                os.replace(staged[relative], target)
    except Exception:
        for relative in reversed(list(backups)):
            target = resolve_under(root, relative)
            backup = backups.get(relative)
            if target.exists() and target.is_file():
                target.unlink()
            if backup is not None and backup.exists():
                target.parent.mkdir(parents=True, exist_ok=True)
                os.replace(backup, target)
        for relative, backup in reversed(list(backups.items())):
            if backup is not None:
                continue
            parent = resolve_under(root, relative).parent
            while parent != root and parent.is_dir() and not any(parent.iterdir()):
                parent.rmdir()
                parent = parent.parent
        raise
    finally:
        if transaction.exists():
            shutil.rmtree(transaction)
        temporary_root = root / ".ai-workflow/.tmp"
        if temporary_root.is_dir() and not any(temporary_root.iterdir()):
            temporary_root.rmdir()
        workflow_root = root / ".ai-workflow"
        if not workflow_existed and workflow_root.is_dir() and not any(workflow_root.iterdir()):
            workflow_root.rmdir()


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Plan, verify, or apply deterministic AI workflow adapters.")
    parser.add_argument("--root", required=True)
    parser.add_argument(
        "--allow-extra-skills",
        action="store_true",
        help="Allow non-built-in Skills while managing only the built-in adapter set.",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--apply", action="store_true")
    parser.add_argument("--json", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        root = Path(args.root).resolve()
        plan = build_adapter_plan(root, allow_extra_skills=args.allow_extra_skills)
        if args.apply:
            if any(operation.action == "conflict" for operation in plan):
                code = 1
            else:
                apply_adapter_plan(root, plan, allow_extra_skills=args.allow_extra_skills)
                code = 0
        elif args.check:
            code = 0 if all(operation.action == "unchanged" for operation in plan) else 1
        else:
            code = 0
        payload = {"mode": "apply" if args.apply else "check" if args.check else "dry-run", "operations": [asdict(operation) for operation in plan]}
        if args.json:
            print(json.dumps(payload, ensure_ascii=False, sort_keys=True))
        else:
            for operation in plan:
                print(f"{operation.action:9} {operation.path}: {operation.reason}")
        return code
    except (OSError, ValueError, UnicodeError) as error:
        payload = {"error": str(error), "type": type(error).__name__}
        if args.json:
            print(json.dumps(payload, ensure_ascii=False, sort_keys=True))
        else:
            print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
